# Etapa 1: Construir a aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiar o arquivo .sln
COPY GestaoEscalaPermutas.sln ./

# Copiar os arquivos .csproj de cada projeto
COPY GestaoEscalaPermutas.Server/GestaoEscalaPermutas.Server.csproj ./GestaoEscalaPermutas.Server/
COPY GestaoEscalaPermutas.Dominio/GestaoEscalaPermutas.Dominio.csproj ./GestaoEscalaPermutas.Dominio/
COPY GestaoEscalaPermuta.Infra/GestaoEscalaPermutas.Infra.csproj ./GestaoEscalaPermuta.Infra/
COPY GestaoEscalaPermutas.Repository/GestaoEscalaPermutas.Repository.csproj ./GestaoEscalaPermutas.Repository/

# Restaurar as dependências
RUN dotnet restore

# Copiar o restante dos arquivos de cada projeto
COPY GestaoEscalaPermutas.Server/ ./GestaoEscalaPermutas.Server/
COPY GestaoEscalaPermutas.Dominio/ ./GestaoEscalaPermutas.Dominio/
COPY GestaoEscalaPermuta.Infra/ ./GestaoEscalaPermuta.Infra/
COPY GestaoEscalaPermutas.Repository/ ./GestaoEscalaPermutas.Repository/

# Copiar o certificado para o container
COPY GestaoEscalaPermutas.Server/certificado.pfx /app/certificado.pfx

# Publicar a aplicação
WORKDIR /app/GestaoEscalaPermutas.Server
RUN dotnet publish -c Release -o out

# Etapa 2: Criar a imagem final
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/GestaoEscalaPermutas.Server/out .

# Copiar o certificado para a imagem final
COPY --from=build /app/certificado.pfx /app/certificado.pfx

# Definir a porta e o comando de execução
EXPOSE 80
ENTRYPOINT ["dotnet", "GestaoEscalaPermutas.Server.dll"]