app = 'back-gestao-escala'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"
  dockerfile = "GestaoEscalaPermutas.Server/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
[env]
  ASPNETCORE_ENVIRONMENT = "Production"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1