# Etapa 1: Construir o frontend
FROM node:18 AS build
WORKDIR /app

# Copiar package.json e package-lock.json (se existir)
COPY package*.json ./

# Instalar dependências
RUN npm install --legacy-peer-deps

# Garantir que a dependência i18next-browser-languagedetector esteja instalada
RUN npm install i18next-browser-languagedetector

# Copiar todos os arquivos restantes
COPY . .

# Build do projeto
RUN npm run build

# Etapa 2: Servidor Nginx final
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Configurar porta dinâmica
ENV PORT=8080
EXPOSE $PORT

CMD sed -i "s/80/$PORT/g" /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'