# ios/Podfile

# Define a versão mínima do iOS
platform :ios, '12.0'

# Configuração do CocoaPods
install! 'cocoapods', :deterministic_uuids => false

# Caminho para o Flutter (necessário para o Codemagic)
flutter_root = File.expand_path(File.join(File.dirname(__FILE__), '..', '.ios', 'Flutter'))
require File.join(flutter_root, 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Adiciona o Firebase Messaging sem modularidade estrita
  pod 'Firebase/Messaging', :modular_headers => false

  # Instala os pods do Flutter
  install_all_flutter_pods(flutter_root)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_post_install(installer) if defined?(flutter_post_install)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end