// <auto-generated />
using System;
using GestaoEscalaPermutas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoEscalaPermutas.Infra.Migrations
{
    [DbContext(typeof(DefesaCivilMaricaContext))]
    [Migration("20250114225438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargos"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NmDescricao")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdCargo")
                        .HasName("PK_IdCargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartamento"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NmDescricao")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdDepartamento")
                        .HasName("PK_IdDepartamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NmEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NrCnpj")
                        .HasColumnType("integer")
                        .HasColumnName("NrCNPJ");

                    b.Property<int>("NrTelefone")
                        .HasColumnType("integer");

                    b.HasKey("IdEmpresa")
                        .HasName("PK_IdEmpresa");

                    b.ToTable("EMPRESA");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Escala", b =>
                {
                    b.Property<int>("IdEscala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscala"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoEscala")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGerada")
                        .HasColumnType("boolean");

                    b.Property<string>("NmNomeEscala")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NrMesReferencia")
                        .HasColumnType("integer");

                    b.Property<int>("NrPessoaPorPosto")
                        .HasColumnType("integer");

                    b.HasKey("IdEscala")
                        .HasName("PK_IdEscala");

                    b.ToTable("Escala");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.EscalaPronta", b =>
                {
                    b.Property<int>("IdEscalaPronta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscalaPronta"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DtDataServico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEscala")
                        .HasColumnType("integer");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("integer");

                    b.Property<int>("IdPostoTrabalho")
                        .HasColumnType("integer");

                    b.HasKey("IdEscalaPronta");

                    b.ToTable("EscalaPronta");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionalidade", b =>
                {
                    b.Property<int>("IdFuncionalidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFuncionalidade"));

                    b.Property<string>("NmDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdFuncionalidade")
                        .HasName("PK_IdFuncionalidade");

                    b.ToTable("Funcionalidades");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("IdCargo")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NmEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NmEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmSenha")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NrMatricula")
                        .HasColumnType("integer");

                    b.Property<long?>("NrTelefone")
                        .HasColumnType("bigint");

                    b.HasKey("IdFuncionario")
                        .HasName("PK_IdFuncionario");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.FuncionarioPerfil", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .HasColumnType("integer");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("integer");

                    b.HasKey("IdFuncionario", "IdPerfil");

                    b.HasIndex("IdPerfil");

                    b.ToTable("FuncionariosPerfis");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuncionalidadeIdFuncionalidade")
                        .HasColumnType("integer");

                    b.Property<int>("FuncionarioIdFuncionario")
                        .HasColumnType("integer");

                    b.Property<int>("IdFuncionalidade")
                        .HasColumnType("integer");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("integer");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoErro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("LogID");

                    b.HasIndex("FuncionalidadeIdFuncionalidade");

                    b.HasIndex("FuncionarioIdFuncionario");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPerfil")
                        .HasName("PK_IdPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.PerfilFuncionalidade", b =>
                {
                    b.Property<int>("IdPerfil")
                        .HasColumnType("integer");

                    b.Property<int>("IdFuncionalidade")
                        .HasColumnType("integer");

                    b.HasKey("IdPerfil", "IdFuncionalidade");

                    b.HasIndex("IdFuncionalidade");

                    b.ToTable("PerfisFuncionalidades");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Permuta", b =>
                {
                    b.Property<int>("IdPermuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermuta"));

                    b.Property<DateOnly?>("DtAprovacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DtDataSolicitadaTroca")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DtSolicitacao")
                        .HasColumnType("date");

                    b.Property<int>("IdEscala")
                        .HasColumnType("integer");

                    b.Property<string>("NmNomeAprovador")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NmNomeSolicitado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NmNomeSolicitante")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NrMatriculaAprovador")
                        .HasColumnType("integer");

                    b.Property<int>("NrMatriculaSolicitado")
                        .HasColumnType("integer");

                    b.Property<int>("NrMatriculaSolicitante")
                        .HasColumnType("integer");

                    b.HasKey("IdPermuta")
                        .HasName("PK_IdPermuta");

                    b.ToTable("Permuta");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.PostoTrabalho", b =>
                {
                    b.Property<int>("IdPostoTrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPostoTrabalho"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NmEnderco")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdPostoTrabalho")
                        .HasName("PK_IdPostoTrabalho");

                    b.ToTable("PostoTrabalho");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.TipoEscala", b =>
                {
                    b.Property<int>("IdTipoEscala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoEscala"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExpediente")
                        .HasColumnType("boolean");

                    b.Property<string>("NmDescricao")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NrHorasFolga")
                        .HasColumnType("integer");

                    b.Property<int>("NrHorasTrabalhada")
                        .HasColumnType("integer");

                    b.HasKey("IdTipoEscala")
                        .HasName("PK_IdTipoEscala");

                    b.ToTable("TipoEscala");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.FuncionarioPerfil", b =>
                {
                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Perfil", "Perfil")
                        .WithMany("FuncionariosPerfis")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Log", b =>
                {
                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionalidade", "Funcionalidade")
                        .WithMany()
                        .HasForeignKey("FuncionalidadeIdFuncionalidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioIdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionalidade");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.PerfilFuncionalidade", b =>
                {
                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionalidade", "Funcionalidade")
                        .WithMany("PerfisFuncionalidades")
                        .HasForeignKey("IdFuncionalidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Perfil", "Perfil")
                        .WithMany("PerfisFuncionalidades")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionalidade");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Funcionalidade", b =>
                {
                    b.Navigation("PerfisFuncionalidades");
                });

            modelBuilder.Entity("GestaoEscalaPermutas.Infra.Data.EntitiesDefesaCivilMarica.Perfil", b =>
                {
                    b.Navigation("FuncionariosPerfis");

                    b.Navigation("PerfisFuncionalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
