name: Build and deploy ASP.Net Core app to Azure Web App - BackendGestaoEscala

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permissão para publicar pacotes/imagens

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Fazer login no Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Passo 3: Construir e publicar a imagem Docker
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/gestaoescala-backend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gestaoescala-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Passo 1: Fazer login no Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Passo 2: Implantar a imagem no Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BackendGestaoEscala'
          slot-name: 'Production'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/gestaoescala-backend:latest'
